export const environment = {
    appComponentTitle : "angular-app",
    apiEndpoint: 'http://localhost:3000/api',
    apiAuthorizationType: 'Bearer',
    apiAuthorization : 'Authorization',
    urlArtistId: "artistId",
    urlArtistIdParameter : ":artistId/",
    urlArtistIdParameterWithoutSlash : ":artistId",
    urlPaintingId: "paintingId",
    urlPaintingIdParameter: ":paintingId/",
    urlPaintingIdParameterWithoutSlash: ":paintingId",
    urlArtistIdWithSlash: "artistId/",
    urlPaintingIdWithSlash: "paintingId/",
    artists: "artists",
    artistsUrl: "artists/",
    slashArtists : "/artists",
    artistsWith2Slash : "/artists/",
    paintingsUrl: "paintings/",
    paintingsWith2Slash : "/paintings/",
    slashPaintings : "/paintings",
    rootUrl : '',
    newArtist : "new-artist",
    newPainting: "new-painting",
    edit : "edit",
    successMessage : "Success",
    failedMessage : "Failed",
    register : "register",
    login : "login",
    bearerWithSpace : "Bearer ",
    token : "token",
    slashUser: "/user",
    slashLogin: "/login",
    slashRegister: "/register",
    authorization : 'Authorization'
};
